/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const setup_logging: () => void;
export const __wbg_httpreader_free: (a: number, b: number) => void;
export const httpreader_new: (a: number, b: number) => number;
export const httpreader_select_all: (a: number) => any;
export const httpreader_select_bbox: (a: number, b: number, c: number, d: number, e: number) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const closure287_externref_shim: (a: number, b: number, c: any) => void;
export const closure304_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
